Repository AC-corporation/server, pull requests merged in 2023-12, with the labels that each got.

#33 [Chore] controller return type 수정
  .idea/libraries/Gradle__com_fasterxml_jackson_dataformat_jackson_dataformat_yaml_2_15_2.xml
  .idea/libraries/Gradle__com_google_code_findbugs_jsr305_3_0_2.xml
  .idea/libraries/Gradle__com_google_guava_failureaccess_1_0_1.xml
  .idea/libraries/Gradle__com_google_j2objc_j2objc_annotations_1_3.xml
  .idea/libraries/Gradle__io_github_classgraph_classgraph_4_8_149.xml
  .idea/libraries/Gradle__io_springfox_springfox_core_2_9_2.xml
  .idea/libraries/Gradle__io_springfox_springfox_spi_2_9_2.xml
  .idea/libraries/Gradle__io_springfox_springfox_spring_web_2_9_2.xml
  .idea/libraries/Gradle__io_springfox_springfox_swagger_ui_2_9_2.xml
  .idea/libraries/Gradle__io_swagger_core_v3_swagger_annotations_2_2_8.xml
  .idea/libraries/Gradle__io_swagger_core_v3_swagger_annotations_jakarta_2_2_7.xml
  .idea/libraries/Gradle__io_swagger_core_v3_swagger_core_2_2_8.xml
  .idea/libraries/Gradle__io_swagger_core_v3_swagger_core_jakarta_2_2_7.xml
  .idea/libraries/Gradle__io_swagger_core_v3_swagger_models_2_2_8.xml
  .idea/libraries/Gradle__io_swagger_core_v3_swagger_models_jakarta_2_2_7.xml
  .idea/libraries/Gradle__org_checkerframework_checker_qual_3_12_0.xml
  .idea/libraries/Gradle__org_springdoc_springdoc_openapi_common_1_6_15.xml
  .idea/libraries/Gradle__org_springdoc_springdoc_openapi_starter_common_2_0_2.xml
  .idea/libraries/Gradle__org_springdoc_springdoc_openapi_starter_webmvc_api_2_0_2.xml
  .idea/libraries/Gradle__org_springdoc_springdoc_openapi_starter_webmvc_ui_2_0_2.xml
  .idea/libraries/Gradle__org_springdoc_springdoc_openapi_ui_1_6_15.xml
  .idea/libraries/Gradle__org_springdoc_springdoc_openapi_webmvc_core_1_6_15.xml
  .idea/libraries/Gradle__org_springframework_plugin_spring_plugin_core_1_2_0_RELEASE.xml
  .idea/libraries/Gradle__org_springframework_plugin_spring_plugin_metadata_1_2_0_RELEASE.xml
  .idea/libraries/Gradle__org_webjars_swagger_ui_4_17_1.xml
  .idea/libraries/Gradle__org_webjars_webjars_locator_core_0_52.xml
  .idea/modules/all-clear.test.iml
  .idea/modules/com.example.all-clear.main.iml
  build.gradle
  src/main/java/all/clear/controller/GradeController.java
  src/main/java/all/clear/controller/RequirementController.java
  src/main/java/all/clear/dto/responseDto/GradeDto.java
  src/main/java/all/clear/dto/responseDto/GradeResponseDto.java
  src/main/java/all/clear/dto/responseDto/SemesterGradeDto.java
  src/main/java/all/clear/dto/responseDto/SemesterGradeResponseDto.java
  src/main/java/all/clear/dto/responseDto/SemesterSubjectDto.java
  src/main/java/all/clear/dto/responseDto/SemesterSubjectResponseDto.java
  src/main/java/all/clear/global/config/SwaggerConfig.java
  src/main/java/all/clear/service/GradeService.java
  src/main/java/all/clear/service/RequirementService.java
Labels: Chore, 다은's work ❤️

#34 [Add] 회원가입, 로그인 기능 구현
  src/main/java/all/clear/controller/UserController.java
  src/main/java/all/clear/domain/User.java
  src/main/java/all/clear/dto/requestDto/LoginRequesetDto.java
  src/main/java/all/clear/dto/requestDto/UserSignupRequestDto.java
  src/main/java/all/clear/repository/UserRepository.java
  src/main/java/all/clear/service/UserService.java
Labels: Add, 다은's work ❤️

#35 [Refector] User를 Member으로 리펙토링
  src/main/java/all/clear/repository/MemberRepository.java
Labels: Refactor

#36 Add/requirement
  src/main/java/all/clear/controller/CrwalController.java
  src/main/java/all/clear/crwal/CrawlMemberInfo.java
  src/main/java/all/clear/crwal/CrawlToEntity.java
  src/main/java/all/clear/crwal/ParsingRequirement.java
  src/main/java/all/clear/service/MemberService.java
  src/main/java/all/clear/service/RequirementService.java
Labels: Feat, Chore, Add, 찬민's work ✅

#37 [ Chore] CralMemberInfo 코드 스타일 수정
  src/main/java/all/clear/controller/GradeController.java
  src/main/java/all/clear/controller/RequirementController.java
  src/main/java/all/clear/crwal/CrawlMemberInfo.java
  src/main/java/all/clear/crwal/ParsingRequirement.java
  src/main/java/all/clear/dto/responseDto/grade/GradeResponseDto.java
  src/main/java/all/clear/dto/responseDto/grade/SemesterGradeResponseDto.java
  src/main/java/all/clear/dto/responseDto/grade/SemesterSubjectResponseDto.java
  src/main/java/all/clear/dto/responseDto/requirement/RequirementComponentResponseDto.java
  src/main/java/all/clear/dto/responseDto/requirement/RequirementResponseDto.java
  src/main/java/all/clear/service/GradeService.java
  src/main/java/all/clear/service/MemberService.java
  src/main/java/all/clear/service/RequirementService.java
  src/test/java/all/clear/CrawalTest.java
  src/test/java/all/clear/RequirementTest.java
Labels: Chore, 현근's work ❄️

#41 [Feat] 회원 탈퇴 및 유저 조회 구현, 크롤링 실패 처리 코드 추가
  src/main/java/all/clear/controller/MemberController.java
  src/main/java/all/clear/crawl/CrawlMemberInfo.java
  src/main/java/all/clear/domain/Member.java
  src/main/java/all/clear/domain/TimeTable.java
  src/main/java/all/clear/domain/TimeTableSubject.java
  src/main/java/all/clear/domain/UserDetailsImpl.java
  src/main/java/all/clear/domain/subject/ActualSubject.java
  src/main/java/all/clear/domain/subject/Subject.java
  src/main/java/all/clear/dto/responseDto/MemberResponseDto.java
  src/main/java/all/clear/global/exception/GlobalErrorCode.java
  src/main/java/all/clear/service/MemberService.java
Labels: Feat, 현근's work ❄️

#45 [Feat] 성적 크롤링 데이터 파싱 함수 구현
  .idea/misc.xml
  src/main/java/allclear/crawl/CrawlMemberInfo.java
  src/main/java/allclear/crawl/ParsingGrade.java
  src/main/java/allclear/domain/grade/SemesterGrade.java
Labels: Feat, Chore, 찬민's work ✅

#47 [Chore] Parsing 함수 에러 처리
  src/main/java/allclear/crawl/CrawlMemberInfo.java
  src/main/java/allclear/crawl/ParsingGrade.java
  src/main/java/allclear/crawl/ParsingRequirement.java
  src/test/java/allclear/CrawalTest.java
  src/test/java/allclear/ParsingTest.java
Labels: Chore, 찬민's work ✅

#48 [Chore] 로그인 예외 처리
  src/main/java/allclear/crawl/CrawlMemberInfo.java
  src/main/java/allclear/crawl/ParsingRequirement.java
Labels: Chore, 찬민's work ✅

#50 [Fix] Email
  .gradle/8.2.1/executionHistory/executionHistory.bin
  .gradle/8.2.1/executionHistory/executionHistory.lock
  .gradle/8.2.1/fileHashes/fileHashes.bin
  .gradle/8.2.1/fileHashes/fileHashes.lock
  .gradle/8.2.1/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/outputFiles.bin
  .gradle/file-system.probe
  .gradle/workspace-id.txt.lock
  .idea/libraries/Gradle__io_springfox_springfox_core_2_9_2.xml
  .idea/libraries/Gradle__io_springfox_springfox_schema_2_9_2.xml
  .idea/libraries/Gradle__io_springfox_springfox_spi_2_9_2.xml
  .idea/libraries/Gradle__io_springfox_springfox_spring_web_2_9_2.xml
  .idea/libraries/Gradle__io_springfox_springfox_swagger2_2_9_2.xml
  .idea/libraries/Gradle__io_springfox_springfox_swagger_common_2_9_2.xml
  .idea/libraries/Gradle__io_springfox_springfox_swagger_ui_2_9_2.xml
  .idea/libraries/Gradle__io_swagger_swagger_annotations_1_5_20.xml
  .idea/libraries/Gradle__io_swagger_swagger_models_1_5_20.xml
  .idea/libraries/Gradle__org_mapstruct_mapstruct_1_2_0_Final.xml
  .idea/libraries/Gradle__org_springframework_plugin_spring_plugin_core_1_2_0_RELEASE.xml
  .idea/libraries/Gradle__org_springframework_plugin_spring_plugin_metadata_1_2_0_RELEASE.xml
  .idea/modules/all-clear.test.iml
  .idea/modules/com.example.all-clear.main.iml
  src/main/java/allclear/domain/EmailCode.java
  src/main/java/allclear/global/config/EmailConfig.java
  src/main/java/allclear/global/exception/code/GlobalErrorCode.java
  src/main/java/allclear/repository/EmailCodeRepository.java
  src/main/java/allclear/service/MemberService.java
  src/main/resources/application.yml
Labels: Fix, 다은's work ❤️

#51 feat : CrawlSubjectInfo 과목 크롤링 기능 추가
  src/main/java/allclear/crawl/CrawlSubjectInfo.java
  src/test/java/allclear/crawl/CrawlSubjectTest.java
Labels: Feat, 찬민's work ✅

#52 [Feat] 시간표 및 과목 구현
  src/main/java/allclear/crawl/ParsingGrade.java
  src/main/java/allclear/domain/grade/Grade.java
  src/main/java/allclear/domain/member/Member.java
  src/main/java/allclear/domain/subject/Subject.java
  src/main/java/allclear/domain/timetable/TimeTable.java
  src/main/java/allclear/domain/timetable/TimeTableSubject.java
  src/main/java/allclear/domain/timetable/Timetable.java
  src/main/java/allclear/domain/timetable/TimetableSubject.java
  src/main/java/allclear/dto/responseDto/SubjectResponseDto.java
  src/main/java/allclear/dto/responseDto/grade/GradeResponseDto.java
  src/main/java/allclear/dto/responseDto/timetable/TimetableResponseDto.java
  src/main/java/allclear/dto/responseDto/timetable/TimetableSubjectResponseDto.java
  src/main/java/allclear/repository/SubjectRepository.java
  src/main/java/allclear/repository/TimetableRepository.java
  src/main/java/allclear/service/SubjectService.java
  src/main/java/allclear/service/TimetableService.java
  src/main/resources/application.yml
Labels: Feat, 현근's work ❄️

#54 [Fix] 유저 Update 수정
  src/main/java/allclear/controller/MemberController.java
  src/main/java/allclear/global/exception/code/GlobalErrorCode.java
  src/main/java/allclear/service/MemberService.java
  src/main/resources/application.yml
  src/test/java/allclear/MemberServiceTest.java
Labels: Fix, 현근's work ❄️
