Repository AC-corporation/server, pull requests merged in 2023-11, with the labels that each got.

#22 [Add] 졸업요건 관련 DTO, ResponseDto 추가
  src/main/java/all/clear/controller/RequirementController.java
  src/main/java/all/clear/controller/SubjectController.java
  src/main/java/all/clear/controller/TimeTableController.java
  src/main/java/all/clear/controller/UserController.java
  src/main/java/all/clear/dto/responseDto/RequirementComponentResponseDto.java
  src/main/java/all/clear/dto/responseDto/RequirementResponseDto.java
  src/main/java/all/clear/global/exception/ErrorResponseDto.java
  src/main/java/all/clear/global/exception/ExceptionAdvice.java
  src/main/java/all/clear/global/exception/GlobalErrorCode.java
  src/main/java/all/clear/global/exception/GlobalException.java
  src/main/java/all/clear/global/exception/GlobalExceptionHandler.java
  src/main/java/all/clear/global/exception/ResponseDto.java
  src/main/java/all/clear/global/exception/SuccessCode.java
  src/main/java/all/clear/global/response/ApiResponse.java
  src/main/java/all/clear/repository/RequirementRepository.java
  src/main/java/all/clear/service/RequirementService.java
  src/test/java/all/clear/RequirementTest.java
Labels: Add, 다은's work ❤️

#27 add : 크롤링 컨틀롤러 추가
  .gradle/8.2.1/executionHistory/executionHistory.bin
  .gradle/8.2.1/executionHistory/executionHistory.lock
  .gradle/8.2.1/fileHashes/fileHashes.bin
  .gradle/8.2.1/fileHashes/fileHashes.lock
  .gradle/8.2.1/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/file-system.probe
  .idea/misc.xml
  build/classes/java/main/all/clear/domain/TimeTable.class
  build/classes/java/main/all/clear/domain/User.class
  build/classes/java/main/all/clear/dto/responseDto/RequirementResponseDto$RequirementResponseDtoBuilder.class
  build/classes/java/main/all/clear/global/exception/ErrorResponseDto$ErrorResponseDtoBuilder.class
  build/classes/java/main/all/clear/global/exception/ResponseDto$ResponseDtoBuilder.class
  build/classes/java/main/all/clear/repository/RequirementRepository.class
  build/classes/java/main/all/clear/repository/SemesterGradeRepository.class
  build/classes/java/main/all/clear/repository/TimeTableRepository.class
  build/classes/java/main/all/clear/service/RequirementComponentService.class
  build/classes/java/main/all/clear/service/RequirementService.class
  build/classes/java/main/all/clear/service/SemesterGradeService.class
  build/classes/java/main/all/clear/service/TimeTableService.class
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/all/clear/controller/CrwalController.java
  src/main/java/all/clear/controller/UserIdPwdForm.java
  src/main/java/all/clear/repository/GradeRepository.java
  src/main/java/all/clear/repository/RequirementRepository.java
Labels: Add

#28 feat : 크롤링 데이터 엔티티 변환 메서드 추가
  .gradle/8.2.1/executionHistory/executionHistory.bin
  .gradle/8.2.1/executionHistory/executionHistory.lock
  .gradle/8.2.1/fileHashes/fileHashes.bin
  .gradle/8.2.1/fileHashes/fileHashes.lock
  .gradle/8.2.1/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  src/main/java/all/clear/controller/CrwalController.java
  src/main/java/all/clear/crwal/CrwalToEntity.java
  src/main/java/all/clear/service/RequirementService.java
Labels: Feat, Add, 찬민's work ✅

#32 chore : 크롤링 태그 경로 변경
  .gradle/8.2.1/executionHistory/executionHistory.bin
  .gradle/8.2.1/executionHistory/executionHistory.lock
  .gradle/8.2.1/fileHashes/fileHashes.bin
  .gradle/8.2.1/fileHashes/fileHashes.lock
  .gradle/8.2.1/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/outputFiles.bin
  .gradle/file-system.probe
  build/classes/java/main/all/clear/crwal/CrwalUserInfo.class
  build/classes/java/main/all/clear/domain/User.class
  build/classes/java/main/all/clear/dto/responseDto/RequirementResponseDto$RequirementResponseDtoBuilder.class
  build/classes/java/main/all/clear/global/exception/ErrorResponseDto$ErrorResponseDtoBuilder.class
  build/classes/java/main/all/clear/global/exception/ResponseDto$ResponseDtoBuilder.class
  build/classes/java/test/all/clear/crwalTest.class
  build/tmp/compileTestJava/previous-compilation-data.bin
  src/main/java/all/clear/crwal/CrwalUserInfo.java
  src/test/java/all/clear/crwalTest.java
Labels: Test, Chore, 찬민's work ✅
