Repository AC-corporation/server, pull requests merged in 2024-02, with the labels that each got.

#89 [Fix:]과목 크롤링 에러 처리
  src/main/java/allclear/crawl/CrawlSubjectInfo.java
  src/main/java/allclear/crawl/ParsingSubject.java
  src/test/java/allclear/MemberServiceTest.java
  src/test/java/allclear/crawl/CrawalTest.java
  src/test/java/allclear/crawl/CrawlSubjectTest.java
Labels: Fix, 찬민's work ✅

#90 [Chore] testUser 비밀번호 수정
  src/main/java/allclear/service/MemberService.java
Labels: Chore, 현근's work ❄️

#91 [Chore] memberService 수정
  src/main/java/allclear/service/MemberService.java
Labels: Chore, 현근's work ❄️

#92 [Fix] 크롤링 에러 처리
  src/main/java/allclear/crawl/CrawlMemberInfo.java
  src/test/java/allclear/crawl/CrawalTest.java
Labels: Fix, 찬민's work ✅

#93 [Refactor] builder 패턴 적용
  src/main/java/allclear/controller/GradeController.java
  src/main/java/allclear/controller/RequirementController.java
  src/main/java/allclear/crawl/ParsingGrade.java
  src/main/java/allclear/domain/grade/Grade.java
  src/main/java/allclear/domain/grade/SemesterGrade.java
  src/main/java/allclear/domain/grade/SemesterSubject.java
  src/main/java/allclear/domain/requirement/Requirement.java
  src/main/java/allclear/domain/requirement/RequirementComponent.java
  src/main/java/allclear/dto/responseDto/grade/GradeResponseDto.java
  src/main/java/allclear/dto/responseDto/grade/SemesterGradeResponseDto.java
  src/main/java/allclear/dto/responseDto/grade/SemesterSubjectResponseDto.java
  src/main/java/allclear/dto/responseDto/requirement/RequirementComponentResponseDto.java
  src/main/java/allclear/dto/responseDto/requirement/RequirementResponseDto.java
  src/main/java/allclear/service/GradeService.java
  src/main/java/allclear/service/MemberService.java
  src/main/java/allclear/service/RequirementService.java
  src/test/java/allclear/crawl/RequirementTest.java
Labels: Refactor

#94 [Fix] 크롤링 에러 수정
  src/main/java/allclear/crawl/CrawlMemberInfo.java
  src/main/java/allclear/crawl/ParsingGrade.java
  src/main/java/allclear/crawl/ParsingRequirement.java
  src/main/java/allclear/domain/grade/Grade.java
  src/main/java/allclear/domain/grade/SemesterGrade.java
  src/main/java/allclear/domain/requirement/Requirement.java
  src/test/java/allclear/crawl/CrawalTest.java
Labels: Fix, 찬민's work ✅

#95 [Add] 과목 추천 메서드
  src/main/java/allclear/controller/TimetableGeneratorController.java
  src/main/java/allclear/domain/timetableGenerator/TimetableGenerator.java
  src/main/java/allclear/domain/timetableGenerator/TimetableGeneratorSubject.java
  src/main/java/allclear/domain/timetableGenerator/TimetableGeneratorTimetable.java
  src/main/java/allclear/domain/timetableGenerator/TimetableGeneratorTimetableSubject.java
  src/main/java/allclear/dto/responseDto/timetable/TimetableResponseDto.java
  src/main/java/allclear/dto/responseDto/timetableGenerator/Step3to6ResponseDto.java
  src/main/java/allclear/repository/subject/SubjectSpecification.java
  src/main/java/allclear/service/TimetableGeneratorManager.java
Labels: Add, 현근's work ❄️

#103 [Chore] Timetable CURD 기능만 구현
  src/main/java/allclear/controller/TimetableController.java
  src/main/java/allclear/domain/timetable/Timetable.java
  src/main/java/allclear/domain/timetable/TimetableSubject.java
  src/main/java/allclear/dto/requestDto/timetable/AddCustomTimetableSubjectRequestDto.java
  src/main/java/allclear/dto/requestDto/timetable/AddTimetableSubjectRequestDto.java
  src/main/java/allclear/dto/requestDto/timetable/TimetableSubjectRequestDto.java
  src/main/java/allclear/dto/requestDto/timetable/UpdateTimetableRequestDto.java
  src/main/java/allclear/dto/requestDto/timetableGenerator/Step2RequestDto.java
  src/main/java/allclear/service/TimetableService.java
Labels: Chore

#107 chore: 과목 생성, 업데이트 API 통일
  src/main/java/allclear/controller/AdminController.java
  src/main/java/allclear/controller/SubjectController.java
  src/main/java/allclear/dto/requestDto/subject/CreateSubjectRequestDto.java
  src/main/java/allclear/dto/requestDto/subject/InitSubjectRequestDto.java
  src/main/java/allclear/dto/requestDto/subject/SubjectSearchRequestDto.java
  src/main/java/allclear/service/SubjectService.java
  src/test/java/allclear/SubjectServiceTest.java
Labels: Chore, 현근's work ❄️

#110 [Fix] 크롤링 에러 수정
  src/main/java/allclear/crawl/CrawlSubjectInfo.java
  src/main/java/allclear/crawl/ParsingSubject.java
  src/main/java/allclear/domain/subject/ClassInfo.java
  src/test/java/allclear/crawl/CrawalTest.java
Labels: Fix, 찬민's work ✅

#118 [Refactor] 회원가입 및 업데이트 api 수정
  src/main/java/allclear/controller/MemberController.java
  src/main/java/allclear/crawl/CrawlMemberInfo.java
  src/main/java/allclear/crawl/Grade/CrawlGradeAndCurriculumInfo.java
  src/main/java/allclear/crawl/Grade/ParsingGrade.java
  src/main/java/allclear/crawl/LoginUsaint.java
  src/main/java/allclear/crawl/Requirement/CrawlRequirementInfo.java
  src/main/java/allclear/crawl/Requirement/ParsingRequirement.java
  src/main/java/allclear/crawl/subject/CrawlSubjectInfo.java
  src/main/java/allclear/crawl/subject/ParsingSubject.java
  src/main/java/allclear/domain/member/Member.java
  src/main/java/allclear/domain/requirement/Requirement.java
  src/main/java/allclear/service/MemberService.java
  src/main/java/allclear/service/SubjectService.java
  src/test/java/allclear/crawl/CrawalTest.java
  src/test/java/allclear/crawl/CrawlSubjectTest.java
  src/test/java/allclear/crawl/ParsingTest.java
  src/test/java/allclear/crawl/RequirementTest.java
Labels: Refactor, 찬민's work ✅

#121 [ Add] 시간표 생성 함수
  src/main/java/allclear/domain/timetableGenerator/TimetableGeneratorSubject.java
  src/main/java/allclear/domain/timetableGenerator/TimetableGeneratorTimetable.java
  src/main/java/allclear/service/TimetableGeneratorManager.java
  src/test/java/allclear/TimetableGeneratorTest.java
  src/test/resources/application.yml
Labels: Add, 현근's work ❄️

#122 [Fix] 과목 크롤링 에러 처리
  src/main/java/allclear/crawl/subject/CrawlSubjectInfo.java
  src/main/java/allclear/crawl/subject/ParsingSubject.java
Labels: Fix

#124 [Feat] 성적 업데이트 서버 실행 시 오류 처리
  src/main/java/allclear/crawl/Grade/CrawlGradeAndCurriculumInfo.java
  src/main/java/allclear/crawl/LoginUsaint.java
  src/test/java/allclear/crawl/CrawalTest.java
Labels: Fix, 찬민's work ✅

#126 [Fix]과목 업데이트 서버 실행 오류 처리
  src/main/java/allclear/crawl/subject/CrawlSubjectInfo.java
Labels: Fix, 찬민's work ✅

#127 Fix: 과목 업데이트 함수 오류 처리
  src/main/java/allclear/service/SubjectService.java
Labels: Fix, 찬민's work ✅

#128 [Chore]
  src/main/java/allclear/service/MemberService.java
  src/main/java/allclear/service/TimetableService.java
  src/main/java/allclear/service/timetableGenerator/TimetableGeneratorManager.java
  src/main/java/allclear/service/timetableGenerator/TimetableGeneratorService.java
Labels: Chore

#129 [Fix] 컴파일 오류 수정
  src/main/java/allclear/controller/MemberController.java
Labels: Fix

#130 [Fix] 학년 설정 수정
  src/main/java/allclear/service/timetableGenerator/TimetableGeneratorService.java
Labels: Fix

#133 [Chore] 시간표 생성기 알고리즘 수정
  src/main/java/allclear/controller/TimetableGeneratorController.java
  src/main/java/allclear/domain/timetableGenerator/TimetableGeneratorSubject.java
  src/main/java/allclear/dto/requestDto/timetableGenerator/Step7RequestDto.java
  src/main/java/allclear/dto/responseDto/timetableGenerator/Step8ResponseDto.java
  src/main/java/allclear/global/exception/code/GlobalErrorCode.java
  src/main/java/allclear/repository/timetableGenerator/TimetableGeneratorTimetableRepository.java
  src/main/java/allclear/service/timetableGenerator/TimetableGeneratorManager.java
  src/main/java/allclear/service/timetableGenerator/TimetableGeneratorService.java
Labels: Chore

#136 [Feat] 교과영역 구분 크롤링 추가 및 과목 업데이트 함수 오류 처리
  src/main/java/allclear/crawl/subject/CrawlSubjectInfo.java
  src/main/java/allclear/crawl/subject/ParsingSubject.java
  src/main/java/allclear/domain/subject/Subject.java
  src/main/java/allclear/service/SubjectService.java
Labels: Fix, Add, 찬민's work ✅
