Repository AC-corporation/server, pull requests merged in 2024-01, with the labels that each got.

#55 [chore] : CrawlSubjectInfo 과목 크롤링 함수 추가
  src/main/java/allclear/crawl/CrawlSubjectInfo.java
  src/test/java/allclear/crawl/CrawlSubjectTest.java
Labels: Chore, 찬민's work ✅

#57 [Feat] 시간표, 시간표 과목 CURD 구현
  src/main/java/allclear/controller/MemberController.java
  src/main/java/allclear/controller/TimetableController.java
  src/main/java/allclear/domain/member/EmailCode.java
  src/main/java/allclear/domain/subject/Subject.java
  src/main/java/allclear/domain/timetable/Timetable.java
  src/main/java/allclear/domain/timetable/TimetableSubject.java
  src/main/java/allclear/dto/requestDto/member/EmailAuthRequestDto.java
  src/main/java/allclear/dto/requestDto/member/EmailIsValidRequestDto.java
  src/main/java/allclear/dto/requestDto/member/LoginRequestDto.java
  src/main/java/allclear/dto/requestDto/member/MemberSignupRequestDto.java
  src/main/java/allclear/dto/requestDto/member/UpdateMemberRequestDto.java
  src/main/java/allclear/dto/requestDto/timetable/AddCustomTimetableSubjectRequestDto.java
  src/main/java/allclear/dto/requestDto/timetable/AddTimetableSubjectRequestDto.java
  src/main/java/allclear/dto/requestDto/timetable/CreateTimetableRequestDto.java
  src/main/java/allclear/dto/requestDto/timetable/UpdateTimetableRequestDto.java
  src/main/java/allclear/dto/requestDto/timetable/UpdateTimetableSubjectRequestDto.java
  src/main/java/allclear/dto/responseDto/SubjectResponseDto.java
  src/main/java/allclear/dto/responseDto/timetable/TimetableSubjectResponseDto.java
  src/main/java/allclear/repository/grade/GradeRepository.java
  src/main/java/allclear/repository/grade/SemesterGradeRepository.java
  src/main/java/allclear/repository/member/EmailCodeRepository.java
  src/main/java/allclear/repository/member/MemberRepository.java
  src/main/java/allclear/repository/requirement/RequirementRepository.java
  src/main/java/allclear/repository/timetable/TimetableRepository.java
  src/main/java/allclear/repository/timetable/TimetableSubjectRepository.java
  src/main/java/allclear/service/GradeService.java
  src/main/java/allclear/service/MemberService.java
  src/main/java/allclear/service/RequirementService.java
  src/main/java/allclear/service/TimetableService.java
  src/test/java/allclear/MemberServiceTest.java
  src/test/java/allclear/crawl/RequirementTest.java
Labels: Feat, 현근's work ❄️

#58 [Chore] 수업 시간에 따른 데이터 필드 수정
  src/main/java/allclear/domain/subject/ClassInfo.java
  src/main/java/allclear/domain/subject/Subject.java
  src/main/java/allclear/domain/timetable/TimetableSubject.java
  src/main/java/allclear/dto/requestDto/timetable/AddCustomTimetableSubjectRequestDto.java
  src/main/java/allclear/dto/requestDto/timetable/UpdateTimetableSubjectRequestDto.java
  src/main/java/allclear/dto/responseDto/SubjectResponseDto.java
  src/main/java/allclear/dto/responseDto/timetable/ClassInfoDto.java
  src/main/java/allclear/dto/responseDto/timetable/TimetableSubjectResponseDto.java
  src/main/java/allclear/repository/SubjectRepository.java
  src/main/java/allclear/repository/subject/SubjectRepository.java
  src/main/java/allclear/service/SubjectService.java
  src/main/java/allclear/service/TimetableService.java
Labels: Chore, 현근's work ❄️

#59 feat : subject 파싱 함수 추가 및 불필요 코드 수정 및 삭제
  src/main/java/allclear/crawl/CrawlMemberInfo.java
  src/main/java/allclear/crawl/CrawlSubjectInfo.java
  src/main/java/allclear/crawl/CrawlTestInfo.java
  src/main/java/allclear/crawl/ParsingSubject.java
  src/test/java/allclear/crawl/CrawlSpeedExceptionTest.java
  src/test/java/allclear/crawl/CrawlSubjectTest.java
Labels: Feat, Chore, 찬민's work ✅

#60 [Feat] Subject 기능 구현
  src/main/java/allclear/controller/AdminController.java
  src/main/java/allclear/controller/SubjectController.java
  src/main/java/allclear/dto/requestDto/subject/GetSubjectListRequestDto.java
  src/main/java/allclear/repository/subject/SubjectRepository.java
  src/main/java/allclear/repository/subject/SubjectSpecification.java
  src/main/java/allclear/service/SubjectService.java
Labels: Feat, 현근's work ❄️

#70 [Chore] 기타 수정 사항
  src/main/java/allclear/AllClearApplication.java
  src/main/java/allclear/controller/AdminController.java
  src/main/java/allclear/controller/SubjectController.java
  src/main/java/allclear/controller/TimetableController.java
  src/main/java/allclear/crawl/CrawlMemberInfo.java
  src/main/java/allclear/crawl/CrawlSubjectInfo.java
  src/main/java/allclear/crawl/ParsingSubject.java
  src/main/java/allclear/domain/member/Member.java
  src/main/java/allclear/domain/subject/ClassInfo.java
  src/main/java/allclear/domain/timetable/TimetableClassInfo.java
  src/main/java/allclear/dto/requestDto/subject/SubjectListRequestDto.java
  src/main/java/allclear/dto/requestDto/timetable/CreateTimetableRequestDto.java
  src/main/java/allclear/dto/requestDto/timetable/UpdateTimetableSubjectRequestDto.java
  src/main/java/allclear/dto/responseDto/subject/SubjectListResponseDto.java
  src/main/java/allclear/dto/responseDto/subject/SubjectResponseDto.java
  src/main/java/allclear/dto/responseDto/timetable/TimetableSubjectResponseDto.java
  src/main/java/allclear/global/config/SwaggerConfig.java
  src/main/java/allclear/global/exception/code/GlobalErrorCode.java
  src/main/java/allclear/repository/subject/SubjectSpecification.java
  src/main/java/allclear/service/GradeService.java
  src/main/java/allclear/service/MemberService.java
  src/main/java/allclear/service/SubjectService.java
  src/main/java/allclear/service/TimetableService.java
  src/main/java/allclear/service/timetableMaker/SubjectSearchCriteria.java
  src/main/java/allclear/service/timetableMaker/TimetableMaker.java
  src/main/java/allclear/service/timetableMaker/UnavailableTimeRange.java
  src/test/java/allclear/SubjectServiceTest.java
  src/test/java/allclear/crawl/CrawalTest.java
  src/test/java/allclear/crawl/CrawlSubjectTest.java
  src/test/java/allclear/crawl/ParsingTest.java
Labels: Chore, 현근's work ❄️

#72 [Chore] : MemberService 예외 처리
  src/main/java/allclear/crawl/CrawlMemberInfo.java
  src/main/java/allclear/service/MemberService.java
Labels: Chore, 찬민's work ✅

#73 [Fix] 유저 업데이트 오류 수정 및 예외 처리 코드 수정
  src/main/java/allclear/domain/grade/Grade.java
  src/main/java/allclear/domain/grade/SemesterGrade.java
  src/main/java/allclear/domain/member/Member.java
  src/main/java/allclear/domain/requirement/Requirement.java
  src/main/java/allclear/repository/grade/GradeRepository.java
  src/main/java/allclear/repository/requirement/RequirementRepository.java
  src/main/java/allclear/service/MemberService.java
Labels: Fix, Chore, 찬민's work ✅

#75 [Chore] Exception handler 제거 및 Api Response 수정
  src/main/java/allclear/controller/AdminController.java
  src/main/java/allclear/controller/GradeController.java
  src/main/java/allclear/controller/MemberController.java
  src/main/java/allclear/controller/TimetableController.java
  src/main/java/allclear/crawl/CrawlMemberInfo.java
  src/main/java/allclear/global/exception/GlobalExceptionHandler.java
  src/main/java/allclear/global/response/ApiResponse.java
  src/main/java/allclear/service/MemberService.java
  src/main/java/allclear/service/SubjectService.java
Labels: Chore, 다은's work ❤️

#77 [Fix] 과목 업데이트 오류 수정 및 예외 처리
  src/main/java/allclear/controller/SubjectController.java
  src/main/java/allclear/crawl/CrawlMemberInfo.java
  src/main/java/allclear/crawl/CrawlSubjectInfo.java
  src/main/java/allclear/crawl/ParsingSubject.java
  src/main/java/allclear/domain/subject/ClassInfo.java
  src/main/java/allclear/global/exception/code/GlobalErrorCode.java
  src/main/java/allclear/repository/subject/ClassInfoRepository.java
  src/main/java/allclear/service/GradeService.java
  src/main/java/allclear/service/MemberService.java
  src/main/java/allclear/service/RequirementService.java
  src/main/java/allclear/service/SubjectService.java
Labels: Fix, Chore, 찬민's work ✅

#78 [Feat] 과목 조회 페이징 기능 구현
  src/main/java/allclear/controller/SubjectController.java
  src/main/java/allclear/dto/responseDto/subject/SubjectListResponseDto.java
  src/main/java/allclear/repository/subject/SubjectRepository.java
  src/main/java/allclear/service/SubjectService.java
  src/test/java/allclear/SubjectServiceTest.java
Labels: Feat

#79 [Feat] 시간표 생성기 구현
  src/main/java/allclear/controller/TimetableGeneratorController.java
  src/main/java/allclear/domain/member/Member.java
  src/main/java/allclear/domain/timetableGenerator/TimetableGenerator.java
  src/main/java/allclear/domain/timetableGenerator/TimetableGeneratorClassInfo.java
  src/main/java/allclear/domain/timetableGenerator/TimetableGeneratorSubject.java
  src/main/java/allclear/domain/timetableGenerator/TimetableGeneratorTimetable.java
  src/main/java/allclear/dto/requestDto/timetableGenerator/Step1RequestDto.java
  src/main/java/allclear/dto/requestDto/timetableGenerator/Step2RequestDto.java
  src/main/java/allclear/dto/requestDto/timetableGenerator/Step3RequestDto.java
  src/main/java/allclear/dto/requestDto/timetableGenerator/Step3to6requestDto.java
  src/main/java/allclear/dto/requestDto/timetableGenerator/Step4RequestDto.java
  src/main/java/allclear/dto/requestDto/timetableGenerator/Step5RequestDto.java
  src/main/java/allclear/dto/requestDto/timetableGenerator/Step6RequestDto.java
  src/main/java/allclear/dto/requestDto/timetableGenerator/Step7RequestDto.java
  src/main/java/allclear/dto/requestDto/timetableGenerator/Step8RequestDto.java
  src/main/java/allclear/dto/responseDto/subject/ClassInfoResponseDto.java
  src/main/java/allclear/dto/responseDto/timetable/TimetableResponseDto.java
  src/main/java/allclear/dto/responseDto/timetable/TimetableSubjectResponseDto.java
  src/main/java/allclear/dto/responseDto/timetableGenerator/Step3to6ResponseDto.java
  src/main/java/allclear/dto/responseDto/timetableGenerator/Step7ResponseDto.java
  src/main/java/allclear/dto/responseDto/timetableGenerator/Step8ResponseDto.java
  src/main/java/allclear/repository/subject/SubjectSpecification.java
  src/main/java/allclear/repository/timetableGenerator/TimetableGeneratorRepository.java
  src/main/java/allclear/repository/timetableGenerator/TimetableGeneratorSubjectRepository.java
  src/main/java/allclear/repository/timetableGenerator/TimetableGeneratorTimetableRepository.java
  src/main/java/allclear/service/MemberService.java
  src/main/java/allclear/service/SubjectService.java
  src/main/java/allclear/service/timetableGenerator/TimetableGeneratorManager.java
  src/main/java/allclear/service/timetableMaker/SubjectSearchCriteria.java
  src/main/java/allclear/service/timetableMaker/TimetableMaker.java
  src/main/java/allclear/service/timetableMaker/UnavailableTimeRange.java
Labels: Feat, 현근's work ❄️

#83 [Refactor] ApiResponse 데이터 수정
  src/main/java/allclear/controller/TimetableGeneratorController.java
  src/main/java/allclear/global/response/ApiResponse.java
Labels: Refactor, 현근's work ❄️

#84 [Feat]: 입학연도별 교과과정 크롤링 기능 추가
  src/main/java/allclear/crawl/CrawlMemberInfo.java
  src/main/java/allclear/crawl/ParsingGrade.java
  src/test/java/allclear/crawl/CrawalTest.java
Labels: Feat, Fix, Chore, 찬민's work ✅
