Repository AC-corporation/server, pull requests merged in 2024-03, with the labels that each got.

#140 [Chore] 과목 크롤링 오류 수정 및 과목 조회 API 수정
  build.gradle
  build/classes/java/main/allclear/dto/requestDto/subject/SubjectSearchRequestDto.class
  src/main/java/allclear/controller/SubjectController.java
  src/main/java/allclear/crawl/LoginUsaint.java
  src/main/java/allclear/crawl/subject/ChangeToUsaintSubjectName.java
  src/main/java/allclear/crawl/subject/CrawlSubjectInfo.java
  src/main/java/allclear/crawl/subject/ParsingSubject.java
  src/main/java/allclear/domain/subject/Subject.java
  src/main/java/allclear/dto/requestDto/subject/SubjectSearchRequestDto.java
  src/main/java/allclear/dto/responseDto/subject/SubjectListResponseDto.java
  src/main/java/allclear/global/config/QuerydslConfig.java
  src/main/java/allclear/repository/subject/SubjectRepository.java
  src/main/java/allclear/repository/subject/SubjectRepositoryCustom.java
  src/main/java/allclear/repository/subject/SubjectRepositoryImpl.java
  src/main/java/allclear/repository/subject/SubjectSpecification.java
  src/main/java/allclear/service/SubjectService.java
  src/test/java/allclear/SubjectServiceTest.java
  src/test/java/allclear/crawl/CrawalTest.java
Labels: Fix, Chore, Add, 찬민's work ✅

#141 [Fix] 과목 파싱 오류 처리
  src/main/java/allclear/crawl/subject/ChangeToUsaintSubjectName.java
  src/main/java/allclear/crawl/subject/ParsingSubject.java
Labels: Fix, 찬민's work ✅

#142 [Fix]: 과목 조회 함수 오류 수정
  src/main/java/allclear/repository/subject/SubjectRepositoryImpl.java
Labels: Fix, Chore, 찬민's work ✅

#145 [Chore] 시간표 관련 API 수정
  src/main/java/allclear/controller/TimetableController.java
  src/main/java/allclear/domain/member/Member.java
  src/main/java/allclear/dto/responseDto/MemberResponseDto.java
  src/main/java/allclear/dto/responseDto/timetable/TimetableListResponseDto.java
  src/main/java/allclear/service/MemberService.java
  src/main/java/allclear/service/TimetableService.java
Labels: Chore

#146 [Chore] 교양선택 추천 알고리즘 보완
  src/main/java/allclear/repository/subject/SubjectSpecification.java
  src/main/java/allclear/service/timetableGenerator/TimetableGeneratorService.java
Labels: Chore, 현근's work ❄️

#147 [Chore] 과목 조건 requestDto 변수명 변경 및 조건 검색 함수 예외 처리
  src/main/java/allclear/crawl/subject/ChangeToUsaintSubjectName.java
  src/main/java/allclear/dto/requestDto/subject/SubjectSearchRequestDto.java
  src/main/java/allclear/repository/subject/SubjectRepositoryImpl.java
Labels: Fix, Refactor, Chore, 찬민's work ✅

#148 [Fix] 과목 크롤링 함수 오류 처리 및 과목 조회 함수 예외 처리
  build/classes/java/main/allclear/dto/responseDto/MemberResponseDto$MemberResponseDtoBuilder.class
  build/classes/java/main/allclear/dto/responseDto/MemberResponseDto.class
  src/main/java/allclear/crawl/LoginUsaint.java
  src/main/java/allclear/crawl/subject/ChangeToUsaintSubjectName.java
  src/main/java/allclear/crawl/subject/CrawlSubjectInfo.java
  src/main/java/allclear/repository/subject/SubjectRepositoryImpl.java
Labels: Fix, Refactor, 찬민's work ✅

#149 [Add] 중복 크롤링되는 과목 처리 및 성적 학기명 필드 추가
  src/main/java/allclear/crawl/Grade/CrawlGradeAndCurriculumInfo.java
  src/main/java/allclear/crawl/Grade/ParsingGrade.java
  src/main/java/allclear/crawl/subject/CrawlSubjectInfo.java
  src/main/java/allclear/domain/grade/SemesterGrade.java
  src/main/java/allclear/domain/subject/Subject.java
  src/main/java/allclear/dto/responseDto/grade/SemesterGradeResponseDto.java
  src/main/java/allclear/service/SubjectService.java
Labels: Fix, Add, 찬민's work ✅

#150 fix : 크롤링 옵션 수정
  src/main/java/allclear/crawl/subject/CrawlSubjectInfo.java
Labels: Fix

#153 [Fext] 20분 이내로 떨어져 있는 강의 시간대 병합
  .gradle/8.2.1/executionHistory/executionHistory.bin
  .gradle/8.2.1/executionHistory/executionHistory.lock
  .gradle/8.2.1/fileHashes/fileHashes.bin
  .gradle/8.2.1/fileHashes/fileHashes.lock
  .gradle/8.2.1/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/file-system.probe
  build/classes/java/main/allclear/crawl/subject/ParsingSubject.class
  build/tmp/compileJava/compileTransaction/stash-dir/CrawlTestInfo.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/TimetableGeneratorController.class.uniqueId1
  build/tmp/compileJava/compileTransaction/stash-dir/TimetableGeneratorManager.class.uniqueId0
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/allclear/crawl/subject/ParsingSubject.java
Labels: Feat
